### ISSUE TITLE
Error when placing this app after "Filter/Annotate by Season" App

### ISSUE THREAD

**Issue by aklohr** [movestore/rds2csv#13]
I am getting the below error when running the move2 "Write CSV App" immediately after the move2 "Filter/Annotate by Season App".
![image](https://github.com/movestore/rds2csv/assets/112666849/8aa2d9eb-b4c4-490f-90ca-89b435c69b52)

I tried running the CSV app immediately after the Movebank Location App and it worked fine.

**Comment by annescharf** [comment]
Hi @aklohr, could you share a workflow with us. It would make debugging faster. Thanks!

**Comment by aklohr** [comment]
Hi @annescharf , I shared the workflow with Andrea this morning and have just shared it with you!

I realized you do not have access to the data I am using (Andrea does). I could not reproduce the error using a random public Movebank study, so I will email the data owner and see if she is willing to add you as a Collaborator to help troubleshoot using this specific workflow and dataset.

**Comment by aklohr** [comment]
@annescharf Update: you have been added to the study and should now be able to run the workflow I shared with you :)

**Comment by andreakoelzsch** [comment]
@annescharf Hi Anne, I have looked into this, and the error occurs, because the track data become list elements in the data frame. write.csv() does not allow that. I remember that we have talked about it before, did you have a solution in the end? I have added the rds that comes out of the workflow from Ashley to the repository and selected it in ".env". If you pull the changes, you should be able to reproduce it locally... thanks!
